name: my_jaspr_web
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  jaspr: ^0.18.2
  jaspr_router: ^0.6.4

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.1.1
  jaspr_builder: ^0.18.2
  jaspr_lints: ^0.3.1
  lints: ^5.0.0

jaspr:
  mode: server

